"""Assembles the page stylesheet: vendored fonts + design tokens + report CSS.

Three parts, in cascade order:
  1. assets/fonts/fonts_inline.css -- @font-face rules with base64 woff2 data
     URIs, generated by scripts/fetch_fonts.py. Nothing here reaches the network.
  2. tokens.root_block()           -- the palette as CSS custom properties.
  3. aecb/render/report.css        -- the stylesheet, referring only to var(--*).

Read once and cached, because the font block alone is ~930 KB and the page is
re-rendered on every Streamlit interaction.
"""

from __future__ import annotations

import os

from . import tokens

_HERE = os.path.dirname(os.path.abspath(__file__))
_ROOT = os.path.dirname(os.path.dirname(_HERE))

FONTS_CSS = os.path.join(_ROOT, "assets", "fonts", "fonts_inline.css")
REPORT_CSS = os.path.join(_HERE, "report.css")

_cache = {}


def _read(path: str) -> str:
    if path not in _cache:
        with open(path, encoding="utf-8") as fh:
            _cache[path] = fh.read()
    return _cache[path]


def font_face_css() -> str:
    """Vendored @font-face rules, or a comment if the bundle is missing.

    A missing bundle is not fatal -- every family in tokens.py carries a system
    fallback, so the page still renders, just not in Archivo/IBM Plex.
    """
    if not os.path.exists(FONTS_CSS):
        return ("/* assets/fonts/fonts_inline.css not found -- run "
                "scripts/fetch_fonts.py on a connected machine. "
                "Falling back to system fonts. */")
    return _read(FONTS_CSS)


def stylesheet() -> str:
    """The complete stylesheet for the report page."""
    return "\n".join([font_face_css(), tokens.root_block(), _read(REPORT_CSS)])


def clear_cache() -> None:
    """Drop cached file contents so edits to report.css show on next render."""
    _cache.clear()
