#!/usr/bin/env bash
#
# Build the offline wheel bundle for the air-gapped Linux server.
#
# Run on a CONNECTED machine (macOS is fine -- this cross-downloads for Linux;
# nothing is compiled locally). Produces wheels/, wheels.tgz and
# wheels.tgz.sha256, which are uploaded to the server with the release.
#
#   bash deploy/build_wheels.sh            # exactly what requirements.lock pins
#   bash deploy/build_wheels.sh --relock   # re-resolve requirements.txt and
#                                          # rewrite requirements.lock
#
# requirements.lock is committed. It pins every package in the tree with a
# sha256 hash, so the default build is reproducible and pip refuses any wheel
# whose hash differs. --relock is the only way the dependency set changes;
# review and commit the new lock afterwards.
#
# Target: CPython 3.9, x86_64 Linux, manylinux2014 (glibc 2.17+).
# Override the architecture with e.g.  PLAT_ARCH=aarch64 bash deploy/build_wheels.sh

set -euo pipefail

cd "$(dirname "$0")/.."

PY_VERSION="3.9"
ABI="cp39"
PLAT_ARCH="${PLAT_ARCH:-x86_64}"
OUT="wheels"
LOCK="requirements.lock"

RELOCK=0
case "${1:-}" in
  "") ;;
  --relock) RELOCK=1 ;;
  *) echo "usage: bash deploy/build_wheels.sh [--relock]" >&2; exit 2 ;;
esac

# Resolve pip via an interpreter rather than the `pip` shim -- under pyenv and
# similar version managers a bare `pip` is often not on PATH.
PYTHON="${PYTHON:-}"
if [ -z "${PYTHON}" ]; then
  for candidate in "./.venv/bin/python" "$(command -v python3 || true)"; do
    if [ -n "${candidate}" ] && [ -x "${candidate}" ] \
       && "${candidate}" -m pip --version >/dev/null 2>&1; then
      PYTHON="${candidate}"
      break
    fi
  done
fi
if [ -z "${PYTHON}" ]; then
  echo "ERROR: no Python with a working pip found. Set PYTHON=/path/to/python." >&2
  exit 1
fi

PLATFORM_ARGS=(
  --only-binary=:all:
  --python-version "${PY_VERSION}"
  --implementation cp
  --abi "${ABI}" --abi abi3 --abi none
  --platform "manylinux_2_17_${PLAT_ARCH}"
  --platform "manylinux2014_${PLAT_ARCH}"
  --platform "manylinux_2_5_${PLAT_ARCH}"
  --platform any
)

echo "==> Target: CPython ${PY_VERSION} / ${ABI} / linux ${PLAT_ARCH}"
echo "==> Using:  ${PYTHON} -m pip"
rm -rf -- "./${OUT}"
mkdir -p "./${OUT}"

# --only-binary=:all: is the point of the exercise: a source archive in the
# bundle would try to compile on a server with no toolchain and no internet.
# Several --platform tags are needed because the dependency tree mixes
# manylinux generations; --platform any picks up the pure-Python wheels.
if [ "${RELOCK}" -eq 1 ]; then
  "${PYTHON}" -m pip download -r requirements.txt -d "./${OUT}" "${PLATFORM_ARGS[@]}"
else
  if [ ! -f "${LOCK}" ]; then
    echo "ERROR: ${LOCK} not found. Run with --relock once to create it." >&2
    exit 1
  fi
  "${PYTHON}" -m pip download --require-hashes --no-deps -r "${LOCK}" \
    -d "./${OUT}" "${PLATFORM_ARGS[@]}"
fi

echo
echo "==> Verifying bundle"
fail=0

# A source archive means pip found no wheel and fell back to source.
shopt -s nullglob
sources=("./${OUT}"/*.tar.gz "./${OUT}"/*.zip)
if [ "${#sources[@]}" -gt 0 ]; then
  echo "  FAIL: source archives present -- these cannot install offline:"
  printf '    %s\n' "${sources[@]}"
  fail=1
else
  echo "  ok: no source archives"
fi

# The packages that ship compiled extensions. One that resolved to the wrong
# ABI or architecture would fail at import time on the server, long after the
# install appeared to succeed.
for pkg in pyarrow numpy pandas pillow protobuf tornado; do
  matches=("./${OUT}"/"${pkg}"-*.whl)
  if [ "${#matches[@]}" -eq 0 ]; then
    echo "  note: ${pkg} not in tree (fine if streamlit dropped it)"
  elif [[ "${matches[0]}" == *"${ABI}"*"${PLAT_ARCH}"* ]]; then
    echo "  ok: $(basename "${matches[0]}")"
  else
    echo "  FAIL: ${pkg} did not resolve to ${ABI}/${PLAT_ARCH}: $(basename "${matches[0]}")"
    fail=1
  fi
done

if [ "${fail}" -ne 0 ]; then
  echo
  echo "Bundle is NOT safe to deploy. Fix the above before uploading." >&2
  exit 1
fi

if [ "${RELOCK}" -eq 1 ]; then
  # Every wheel in the bundle, pinned by version AND sha256. pip's
  # --require-hashes mode then refuses anything that does not match, both
  # here on the next build and on the server at install time.
  "${PYTHON}" - "${OUT}" "${LOCK}" "${PY_VERSION}" "${PLAT_ARCH}" <<'PY'
import hashlib, os, re, sys
out, lock, py_version, arch = sys.argv[1:5]
lines = [
    "# Generated by deploy/build_wheels.sh --relock. Do not edit by hand.",
    "# Every package of the offline bundle (CPython %s, linux %s), pinned by"
    % (py_version, arch),
    "# version and sha256. Installed with pip --require-hashes.",
]
for name in sorted(os.listdir(out), key=str.lower):
    match = re.match(r"([A-Za-z0-9_.]+)-([0-9][^-]*)-.*\.whl$", name)
    if not match:
        continue
    with open(os.path.join(out, name), "rb") as fh:
        digest = hashlib.sha256(fh.read()).hexdigest()
    package = match.group(1).replace("_", "-").lower()
    lines.append("%s==%s \\\n    --hash=sha256:%s" % (package, match.group(2), digest))
with open(lock, "w", encoding="utf-8") as fh:
    fh.write("\n".join(lines) + "\n")
print("  wrote %s (%d pinned packages)" % (lock, len(lines) - 3))
PY
fi

tar czf wheels.tgz "${OUT}"
if command -v sha256sum >/dev/null 2>&1; then
  sha256sum wheels.tgz > wheels.tgz.sha256
else
  shasum -a 256 wheels.tgz > wheels.tgz.sha256
fi

echo
echo "==> Done"
echo "    $(find "./${OUT}" -name '*.whl' | wc -l | tr -d ' ') wheels, $(du -sh "./${OUT}" | cut -f1) in ${OUT}/"
echo "    packaged as wheels.tgz (checksum in wheels.tgz.sha256)"
echo
echo "Next: copy the release archive, wheels.tgz and wheels.tgz.sha256 to the"
echo "      server and follow docs/OPERATIONS.md (deploy/install_offline.sh)."
