"""One-off: vendor the report's webfonts for offline use.

The report is set in Archivo / IBM Plex Sans / IBM Plex Mono, which would otherwise
come from fonts.googleapis.com.
The target server has no internet, so this script must be run ONCE on a connected
machine. It downloads the woff2 files and writes a single self-contained
stylesheet, assets/fonts/fonts_inline.css, with every font embedded as a base64
data: URI.

That file is then read verbatim by aecb.render.css at render time -- no network,
no filesystem lookups from the browser, and the downloaded standalone HTML stays
byte-for-byte self-contained.

Licensing: every family fetched here (Archivo, IBM Plex Sans/Mono/Arabic) is
SIL OFL 1.1. assets/fonts/OFL.txt carries the license text and attribution --
OFL redistribution expects it to accompany the vendored files, and a license
scanner reports the woff2 blobs as unknown-license without it. If a family is
ever added or swapped here, update OFL.txt in the same change.

Run:  python3 scripts/fetch_fonts.py
"""

from __future__ import annotations

import base64
import os
import re
import sys
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
FONT_DIR = os.path.join(ROOT, "assets", "fonts")

# Modern UA so Google serves woff2 rather than legacy ttf.
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
)

# Two requests: the UI families, then Arabic on its own. Arabic is used by a
# single element (.id-name-ar, weight 500) so it needs one weight and only the
# arabic subset -- its latin subsets would duplicate IBM Plex Sans for nothing.
CSS_URLS = [
    (
        "https://fonts.googleapis.com/css2"
        "?family=Archivo:wght@500;600;700;800"
        "&family=IBM+Plex+Mono:wght@400;500;600"
        "&family=IBM+Plex+Sans:wght@400;500;600;700"
        "&display=swap",
        {"latin", "latin-ext"},
    ),
    (
        "https://fonts.googleapis.com/css2"
        "?family=IBM+Plex+Sans+Arabic:wght@500"
        "&display=swap",
        {"arabic"},
    ),
]

BLOCK_RE = re.compile(
    r"/\*\s*(?P<subset>[a-z0-9-]+)\s*\*/\s*(?P<block>@font-face\s*\{[^}]*\})",
    re.IGNORECASE,
)
URL_RE = re.compile(r"url\((?P<url>https://[^)]+\.woff2)\)")


def _get(url: str) -> bytes:
    req = urllib.request.Request(url, headers={"User-Agent": UA})
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.read()


def main() -> int:
    os.makedirs(FONT_DIR, exist_ok=True)

    blocks = []
    for url, keep in CSS_URLS:
        print("Fetching font stylesheet ...")
        css = _get(url).decode("utf-8")
        for m in BLOCK_RE.finditer(css):
            if m.group("subset").lower() in keep:
                blocks.append(m.group("block"))

    if not blocks:
        print("ERROR: no @font-face blocks matched. Google's CSS format may have "
              "changed -- inspect the response manually.", file=sys.stderr)
        return 1

    # Weights of a variable font share one woff2 URL, so cache by URL.
    cache = {}
    out = [
        "/* Vendored webfonts -- generated by scripts/fetch_fonts.py.",
        " * Do not edit by hand. Regenerate on a connected machine.",
        " * Embedded as base64 so the page has zero external references. */",
        "",
    ]

    for block in blocks:
        m = URL_RE.search(block)
        if not m:
            continue
        url = m.group("url")
        if url not in cache:
            print("  downloading %s" % url.rsplit("/", 1)[-1])
            raw = _get(url)
            # Keep the raw file too, so the bundle can be audited.
            with open(os.path.join(FONT_DIR, url.rsplit("/", 1)[-1]), "wb") as fh:
                fh.write(raw)
            cache[url] = base64.b64encode(raw).decode("ascii")
        data_uri = "data:font/woff2;base64,%s" % cache[url]
        out.append(block.replace(url, data_uri))
        out.append("")

    target = os.path.join(FONT_DIR, "fonts_inline.css")
    with open(target, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    size_kb = os.path.getsize(target) / 1024.0
    print("\nWrote %s" % target)
    print("  %d @font-face rules, %d unique woff2 files, %.0f KB"
          % (len(blocks), len(cache), size_kb))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
